name: Run Robot Framework Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install robotframework
          pip install robotframework-requests
          pip install robotframework-seleniumlibrary
          pip install robotframework-stringlibrary
          pip install robotframework-collections

      - name: Run Robot Framework tests
        run: |
          mkdir -p results
          robot --outputdir results /workspaces/APItest_Robot/tests
